--- #YAML:1.0
name:               Geography-Countries
version:            2009040901
abstract:           2-letter, 3-letter, and numerical codes for countries.
author:
    - Abigail <geography-countries@abigail.be>
license:            mit
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:  5.006
resources:
    repository:  git://github.com/Abigail/geography--countries.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - Geography
    - Countries
